### Create client
POST http://localhost:3003/client/create
Content-Type: application/json

{
    "name": "Client3"
}

### Get all clients
GET http://localhost:3003/client/getclients
Content-Type: application/json


### Get all products
GET http://localhost:3003/product/getproducts
Content-Type: application/json


### Get stock
GET http://localhost:3003/product/getstock
Content-Type: application/json


### Create order
POST http://localhost:3003/order/neworder
Content-Type: application/json

{
    "fkClient": "16f7a0de-1e3f-4081-be79-fd0c6a8a5426",
    "deliveryDate":"2023-02-15",
    "productList":[
        {
            "id":1,
            "qty": 2
        },
        {
            "id":10,
            "qty": 3
        }
    ]
}