### Create client
POST http://localhost:3003/client/create
Content-Type: application/json

{
    "name": "Client5"
}

### Get all clients
GET http://localhost:3003/client/getclients
Content-Type: application/json


### Get all products
GET http://localhost:3003/product/getproducts
Content-Type: application/json


### Get stock
GET http://localhost:3003/product/getstock
Content-Type: application/json


### Create order
POST http://localhost:3003/order/neworder
Content-Type: application/json

{
    "fkClient": "06be122a-feeb-4a91-8089-ff10dae3c415",
    "deliveryDate":"2023-02-15",
    "productList":[
        {
            "id":1,
            "qty": 2
        },
        {
            "id":10,
            "qty": 3
        }
    ]
}